/* Gates the build output. Run after `npm run build`. */
import { readFileSync, existsSync, statSync } from 'node:fs';
import { globSync } from 'node:fs';
import { relative, join } from 'node:path';

const DIST = 'dist';
const SRC_ROOTS = ['src', 'scripts', 'public/api', 'public/icons', 'public/img'];
const ROOT_FILES = ['README.md', 'astro.config.mjs', 'package.json', '.gitignore'];
const ASSET_EXT = /\.(svg|png|jpe?g|webp|ico|css|js|json|txt|xml|webmanifest)$/i;
const BANNED = /claude|anthropic|generated by|ai-generated|chatgpt|openai|copilot/i;

const read = (f) => readFileSync(f, 'utf8');
const html = globSync(`${DIST}/**/*.html`);
if (html.length === 0) {
  console.error('No HTML in dist. Run `npm run build` first.');
  process.exit(1);
}

const problems = [];
const report = (group, list) => {
  console.log(`[${group.padEnd(7)}] ${list.length}`);
  list.slice(0, 8).forEach((x) => console.log(`    ${x}`));
  problems.push(...list.map((x) => `${group}: ${x}`));
};

/* Pages and their anchors. */
const pages = new Set(['/']);
const anchors = new Map();
for (const f of html.filter((f) => f.endsWith('index.html'))) {
  const p = ('/' + relative(DIST, f).replace(/index\.html$/, '')).replace(/\/+$/, '') + '/';
  pages.add(p);
  anchors.set(p, new Set([...read(f).matchAll(/id="([^"]+)"/g)].map((m) => m[1])));
}

/* Internal links and fragments. */
const linkBad = new Set();
for (const f of html) {
  for (const [, href, frag] of read(f).matchAll(/href="(\/[^"#?]*)(#[^"]*)?"/g)) {
    if (href.startsWith('//') || ASSET_EXT.test(href)) continue;
    const norm = href.endsWith('/') ? href : href + '/';
    if (!pages.has(norm)) linkBad.add(`no page  ${href}${frag ?? ''}`);
    else if (frag && !anchors.get(norm).has(frag.slice(1))) linkBad.add(`no anchor ${href}${frag}`);
  }
}
report('links', [...linkBad].sort());

/* Every local asset a page references must exist. */
const assetBad = new Set();
for (const f of html) {
  for (const [, a] of read(f).matchAll(/(?:src|href|content)="(\/[^"?#]*\.[a-z0-9]+)"/gi)) {
    if (!ASSET_EXT.test(a)) continue;
    if (!existsSync(join(DIST, a))) assetBad.add(a);
  }
}
report('assets', [...assetBad].sort());

/* Nothing authored here may name the tooling used to build it. */
/* This file carries the pattern it searches for, so it excludes itself. */
const SELF = 'scripts/check-dist.mjs';
const files = [
  ...SRC_ROOTS.flatMap((r) => globSync(`${r}/**/*`)),
  ...ROOT_FILES.filter(existsSync),
].filter((f) => f !== SELF && statSync(f).isFile() && statSync(f).size < 3_000_000);
report('hygiene', files.filter((f) => BANNED.test(read(f))));

/* House style. */
report('style', files.filter((f) => f.startsWith('src') && read(f).includes('—')));

/* The placeholder domain must never ship. */
report('domain', html.filter((f) => read(f).includes('stackyard.example')).map((f) => relative(DIST, f)));

console.log(problems.length ? `\nFAIL: ${problems.length} problem(s)` : '\nPASS');
process.exit(problems.length ? 1 : 0);
